lst=['hello','world','python']
print('这里是原始数据：',lst,id(lst))
print('---------------------')
lst.append('sql')
print('增加数据之后：',lst,id(lst))
print('---------------------')
lst.insert(1,100)
print('增加数据之后：',lst,id(lst))
print('---------------------')
lst.remove('world')
print('移除数据之后：',lst,id(lst))
print('---------------------')
lst.pop(1)
print('移除数据之后：',lst,id(lst))
print('---------------------')
# lst.clear()
# print('清除所有数据之后：',lst,id(lst))
lst.reverse()
print('反转数据之后：',lst,id(lst))
print('---------------------')
new_lst=lst.copy()
print('这里是原始数据的副本：',new_lst,id(new_lst))
print('---------------------')
lst[1]='mysql'
print('修改数据之后：',lst,id(lst))
print('---------------------')